### ISSUE TITLE
Fatal error attempting to connect to websocket

### ISSUE THREAD

**Issue by broskoski** [hxrts/spider#1]
After installing the libraries and running `Spider()` I get an error in both Chome and Safari:
```
WebSocket connection to 'ws://127.0.0.1:3328/websocket/' failed: Data frame received after close
```

**Comment by hxrts** [comment]
Hmm, haven't encountered this personally and it's not well documented, but I've added an option to specify the local port in a config.txt file. Maybe that will help if you have a bunch of ports already in use? Also modified the setup and run steps slightly so it's a little simpler.

I don't think anyone else has tried to run it yet so thanks for bearing with me.

**Comment by hxrts** [comment]
so Lukas just had the same issue. I pushed a change which seemed to fix it for him.

**Comment by hxrts** [comment]
pretty sure my changes addressed this, closing for now.
