### ISSUE TITLE
no package called ‘shiny’

### ISSUE THREAD

**Issue by gndclouds** [hxrts/spider#2]
After running `install.packages('pacman') ; source('_daemon.R') ; q(save = 'no')
--- Please select a` and picking mirror for USA [CA1] I got the following error.

`Error in loadNamespace(name) : there is no package called ‘shiny’`

**Comment by hxrts** [comment]
When you get the error, I think you should be dropped into an interactive R session, at which point you should be able to run ```install.packages("shiny")```. Once you exit out of the session (```quit()```) and try again it should work.

If you don't enter the interactive session automatically, you can start one manually by running the command ```R``` and then doing the same ```install.packages("shiny"```, and then exiting with ```quit()``` and trying again.

Let me know how that goes.

**Comment by gndclouds** [comment]
Awesome(!), that worked the server now boots and takes me to the site. But a new error (sorry new to using R).

`[[ level 1 ]]

research-tactics

[[ done ]]
Warning: Error in ..stacktraceon..: object 'token' not found
Stack trace (innermost first):
    60: isolate
    59: observerFunc
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>
ERROR: [on_request_read] connection reset by peer`

Then I get a light translucent overlay over the search interface.

![screen shot 2017-10-08 at 10 53 57 pm](https://user-images.githubusercontent.com/1757261/31326396-9f3840e0-ac7b-11e7-9477-8a87b8e462b9.png)

**Comment by hxrts** [comment]
ah, sorry about that! haven't had anyone testing this, so thanks for your patience.

I added the ability to view private channels a while ago and forgot to document. So the app tries to read a file called ```_secret.R```, which you may need to create in the project root if it's not there. That file should have a single line: ```token = 'your-arena-api-key'```. The api key is going to be a long alpha-numeric string, which you can obtain on the [arena dev page](https://dev.are.na/oauth/applications). Once that file is there, everything should work, and you'll have the option of mapping private channels. Hope that does it!

**Comment by gndclouds** [comment]
That did it! I'll make a pull request of the read me with these changes. Thanks for the help and making spider.

**Comment by hxrts** [comment]
That's great! Hope you find it useful :)
